version: "3.8"
services:
  mysql:
    container_name: mysql
    environment:
      MYSQL_DATABASE:"devops"
      MYSQL_ROOT_PASSWORD:"root"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - two-tier
  flask:
    build:
      context: .
    container_name: two-tier-backend
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: devops
    networks:
      - two-tier
volumes:
  mysql-data:
networks:
  two-tier:

